### PR TITLE
#72 Removing redundant classes

### PR DESCRIPTION
**Pull request by longtimeago**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Please avoid the big merge button, and prefer rebasing commits and pushing them directly to avoid the noisy "diamond merge" commits in history.

**Comment by longtimeago** [comment]
@mickaelistria may I know why do you care so much about commit history? What benefits do we have with clear history (except clear history by itself)?
This rebasing is really complicates things (at least for me).
IMO, PR is introduced as an atomic unit of work, which can be reviewed and merged.

For example, I see  many misprints in the code/javadocs
To fix that instead of just doing a PR I have to do the PR + rebase + DANGEROUS force push.

Another example. I see the bug. I'd like to have at least 2 commits in the history - one for test which reproduces the bug, another - for the fix.

**Comment by mickaelistria** [comment]
The history is the main value of any SCM. Anything that makes the history more difficult to understand and that introduce "noise" is an anti-pattern that reduces the value of using a SCM. The clear history itself has very high value, it's a sufficient reason to avoid "merge" commits without payload.
About rebasing, I suggest you just spend some time getting used to "git pull --rebase", once you understand it, it doesn't require additional work compared to a merge and makes everything simpler.

About the dangerous "force --push", it's an issue with GitHub pull requests, compared to other systems such as Gerrit. It indeed requires some care and good understanding of what's going to happen. It usually works better if you avoid "implicit" push such as `git push --force` and always use instead `git push --force remote HEAD:targetBranch`.

If you're contributing a test + the fix simultaneously in the same PR, there is no benefit in going into a finer grain and separate commits.

For the fun (not mandatory), I've enabled GerritHub for this maven-download-repository: https://review.gerrithub.io/#/admin/projects/maven-download-plugin/maven-download-plugin . Compared to messy GitHub PR, Gerrit is a cleaner approach to code review and encourages all best practices mentioned above rather than GitHub anti-patterns.

**Comment by longtimeago** [comment]
Thanks for the reply and hints.


> The history is the main value of any SCM. Anything that makes the history more difficult to understand and that introduce "noise" is an anti-pattern that reduces the value of using a SCM.

I'm still wondering what is so valuable in the history? History for the history is not an explanation :)

IMO, the main value of any SCM is that it allows many contributors evolve the project **safely** without a possibility of accidentally lost the code.
In our case, any contribution is like a pain, as a contributor should think not only about the code functionality and quality but also about history cleanup and other such things.

**Comment by mickaelistria** [comment]
> I'm still wondering what is so valuable in the history? History for the history is not an explanation :)

For a project such as maven-download-plugin, the history is the changelog that's presented to adopters. I wouldn't like to have to rewrite a human-friendly changelog because of a lot of Merge commits or because of a dozen of commits for the same feature. It's important to keep it readable so we very easily know what changed. I let you compare the history of this plugin with the history of some other project with same activity but using merge commits, and challenge you to summarize what was done in the last year. You'll start hating merge commits ;)
A clean history is also necessary when one wants to track down complex regressions noticed late after they are introduced.

I'm sorry if this feels like a pain, but I find it pretty natural to expect contributors to consider integration in the project as a whole instead of just considering a specific line of code to change.
I wouldl now recommend using the GerritHub instance to contribute to this project.

**Pull request merged**
