### PR TITLE
#75 Fix for non-overwriting the file if no signature specified,  skipCache and overwrite requested

### PR DESCRIPTION
**Pull request by longtimeago**
#75 Reproduced and fixed
@mickaelistria please, review

### CODE REVIEW

**Comment by mickaelistria** [comment]
Good test, and good patch. Thanks!

**Comment by mickaelistria** [comment]
Rebasing seems to be conflicting with formatting changes. Can you please have a look?

**Comment by longtimeago** [comment]
@mickaelistria sure, will do tonight

**Comment by longtimeago** [comment]
@mickaelistria done

**Comment by mickaelistria** [comment]
Merged, thanks.

**Pull request merged**
