### PR TITLE
Resolves #230: Use concurrent calls in ArtifactMojo

### LINKED ISSUE #230: Add concurrency to ArtifactMojo
Depenendency artifact retrieval in ArtifactMojo could benefit a great deal from making the calls concurrent.

### PR DESCRIPTION
**Pull request by ajarmoniuk**
Alternative PR to #227 -- with added concurrency. There are basically no changes to what's been done in #227 except that I've also made it use the Java 8's CompletableFuture API.

It might be not as easy to review as the single threaded version ;) My preliminary tests show great performance improvements.

### CODE REVIEW

**Comment by ajarmoniuk** [comment]
@longtimeago please review

**Comment by ajarmoniuk** [comment]
I mean, it's blazing fast. WOW

Try `invoker.mavenOpts.2 = -DgroupId=org.apache.maven -DartifactId=plexus-utils -Dversion=4.0.0-alpha-2 -DdependencyDepth=4`

**Comment by ajarmoniuk** [comment]
@longtimeago please review

**Review by longtimeago — APPROVED** [review]
@ajarmoniuk uff sorry for such a long delay. Was really busy on another project.
Thanks a lot for the contribution! Looks good to me :)

**Pull request merged**
