### PR TITLE
Rewrote WGet using httpclient

### PR DESCRIPTION
**Pull request by Riduidel**
The goal is to prepare plugin for support of headers/parameters.
For that, http client was chosen due to its high versatility.

Authentication and proxying have been integrated into httpclient construction, as well as support for timeouts. 
Console download monitor is loaded only in interactive mode (as it was before).

Tell me if anything is not ok

### CODE REVIEW

**Comment by mickaelistria** [comment]
@Riduidel Do you know why IT tests are failing? Seems like your patch does introduce a regression somewhere.

This change replaces Wagon by HttpClient. I think it's fine because:
* the goal is named *wget* which is typically http
* the project never really intended nor committed nor documented to support other protocols than http family for this goal
* for those who need something else, a `wagon-maven-plugin` already exists
* The 5 first pages of users on GitHub ( https://github.com/search?l=Maven+POM&q=download-maven-plugin&type=Code&utf8=%E2%9C%93 ) show only HTTP urls
* The main contributors have use-cases which are only about HTTP

@mykelalvis @fpape You contributed changes for proxy and authentication. Could you please check and comment this change to make sure proxy and auth are still working for you?

**Comment by Riduidel** [comment]
I've not yet looked at failures in integration tests ... but they are already present on master (for the most of them). I will look at that.

**Comment by mykelalvis** [comment]
@mickaelistria I don't *think* I did any auth or proxy changes that this affects.

**Comment by ok2c** [comment]
@mickaelistria @longtimeago Would you still be interested in a write of WGet based on Apache HttpClient instead of Maven HTTP wagon?

**Comment by mickaelistria** [comment]
No objection.

**Comment by ok2c** [comment]
@mickaelistria @longtimeago Please note that `ftp` transport will no longer be supported. Please let me know if you are potentially interested in `http/2` transport.

**Comment by mickaelistria** [comment]
I don't have a strong opinion, as I'm not really involved in the development of this plugin these days. All the use-case I personally have are http, so I'm fine with the proposed change. But I'll let @longtimeago have the last word here.

**Comment by longtimeago** [comment]
@mickaelistria @ok2c imo, ftp is never used, so I'm fine with http (with optional http/2 support)

**Comment by ok2c** [comment]
@longtimeago I'll do the first cut with HttpClient 4.5 (GA). Later I can upgrade it to HttpClient 5.0 (BETA) if you decide to support `http/2`.

**Comment by longtimeago** [comment]
closing in favor of https://github.com/maven-download-plugin/maven-download-plugin/pull/123

**Comment by ok2c** [comment]
@mickaelistria @longtimeago Feel free to let me know if you are willing to upgrade to Apache HttpClient 5.0 BETA in order to get `http/2` support. Also, one could support both transports at the same time. HC 4.x and HC 5.x can be co-located in the same application (class loader).

**Comment by longtimeago** [comment]
@ok2c I would avoid using beta version and wait for stable release

**Comment by ok2c** [comment]
@longtimeago This is not uncommon. Please do note, though, that I can slap whatever label on HttpClient release I please. `BETA` status for HttpComponents enables us to tweak the public APIs a little longer. It is not reflective of the code quality or stability.

**Pull request closed without merging**
