### PR TITLE
rise java build requirement to v11 (due to mockito)

### PR DESCRIPTION
**Pull request by longtimeago**
plugin still works in 1.8 projects

### CODE REVIEW

**Comment by pionCham** [comment]
Hello~   I referenced the 1.11.2 version plugin in my project but i found that  it can not work in Java 8 environment.

**Comment by longtimeago** [comment]
@pionCham doh! Very good catch, thank you!
Let me fix that

**Comment by longtimeago** [comment]
@pionCham please, try https://github.com/maven-download-plugin/maven-download-plugin/releases/tag/1.11.3
Hope I didn't mess  it up again :D

**Comment by pionCham** [comment]
> @pionCham please, try https://github.com/maven-download-plugin/maven-download-plugin/releases/tag/1.11.3 Hope I didn't mess it up again :D
Thanks! I will try again and tell you the result later. @longtimeago

**Comment by pionCham** [comment]
> > @pionCham please, try https://github.com/maven-download-plugin/maven-download-plugin/releases/tag/1.11.3 Hope I didn't mess it up again :D
> > Thanks! I will try again and tell you the result later. @longtimeago

Haha, t worked successfully！Thank you . 😊 @longtimeago

**Pull request merged**
