### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by longtimeago** [comment]
@mickaelistria just curious, is the release procedure automated somehow? 
Which steps you usually perform to do it? Is there any manual for that?

**Comment by mickaelistria** [comment]
As I've had bad experiences with the Maven release plugin in the past, I do it manually as described in https://github.com/maven-download-plugin/maven-download-plugin/wiki#doing-a-release

**Comment by longtimeago** [comment]
@mickaelistria Many steps ... 
As I mentioned in some post before, there is a great too (rultor.com), which can to many things, including releases for maven plugin.
If you are interested, please, take a look http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

It's free, and well tested on all maven plugins of the organization https://github.com/jcabi

Just FYI :)

**Comment by longtimeago** [comment]
@mickaelistria and thank you very much for the release!
I'll continue improving the project when I'll have some spare time

**Pull request merged**
