### PR TITLE
Add download.plugin.skip.cache property to skipCache

### PR DESCRIPTION
**Pull request by gastaldi**
@mickaelistria can you review this?

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'd rather call the property download.cache.skip for consistency with other properties

**Comment by mickaelistria** [comment]
Thank you!

**Comment by gastaldi** [comment]
@mickaelistria thanks! Can I expect a release soon?

**Comment by gastaldi** [comment]
Sure, that would be nice. Where can I find the release instructions?

**Comment by mickaelistria** [comment]
They're at https://github.com/maven-download-plugin/maven-download-plugin/wiki#doing-a-release .
I added you to the team.

**Pull request merged**
