### PR TITLE
corrects SHA512 support

### PR DESCRIPTION
**Pull request by sleicht**
So the sha512 support works - proven with the its-profile.

### CODE REVIEW

**Comment by mickaelistria** [comment]
I tried it locally, and couldn't have it test passing...

**Comment by sleicht** [comment]
I forgot to correct the WGet class. I created a new PR https://github.com/maven-download-plugin/maven-download-plugin/pull/46

**Comment by sleicht** [comment]
I don't know why the tests passed on my side but the did...

**Comment by mickaelistria** [comment]
Ok. In such case, it's better that either you add a commit on the branch from when the PR is created (so it's added to the PR) or you can fix your commit by amending it and using "git push --force HEAD:prBranch".

**Comment by sleicht** [comment]
I did a force push but I couldn't reopen this PR.

**Comment by mickaelistria** [comment]
Ok, not a big deal anyway

**Pull request closed without merging**
