### PR TITLE
Addressing issue #48

### PR DESCRIPTION
**Pull request by SirWellington**
https://github.com/maven-download-plugin/maven-download-plugin/issues/48

### CODE REVIEW

**Comment by SirWellington** [comment]
Feedback welcomed.

**Comment by mickaelistria** [comment]
Overall, I'm OK with the feature you're willing to provide and I'd like to see it part of the Mojo.
However, I see several small issues with this PR before it can be merged.
1. Please do not change code style without reason since it adds a lot of "noise" to review without adding value. Stick to the project current code style and avoid change anything (such as whitespaces) in code you didn't work on.
2. I'd rather have a single commit to review/merge for each feature. For this, please amend the initial commit and use "push --force" on your branch to simply update the initial commit in PR without stacking many commits.
3. Such parameters are by convention called "failOnError" in many Maven mojos. Can you please use that name?

**Comment by SirWellington** [comment]
Thank you for taking the time to review my PR.

On point 1, if you take a look at the original source for `Wget.java`, you will see that there is no consistency with the style. For the opening curly braces, sometimes they are on the next line, other times they are on the same line. 

The majority of the code **is** on the next line, so I just stuck to that.

**Comment by mickaelistria** [comment]
Yes, I know about the style, and I'm not forcing you to use a specific style for the code you're adding. It's more that for the parts of code you don't touch, I prefer that the style doesn't get changed. It makes review and search in history much easier.

**Comment by SirWellington** [comment]
Moving to PR #51

**Pull request closed without merging**
