### PR TITLE
removed type check as it prevents any https proxies from working

### PR DESCRIPTION
**Pull request by arykov**
This is proposed fix for #156

### CODE REVIEW

**Comment by guw** [comment]
@mickaelistria Are you still involved in this project? I'd appreciate a merge and service release. Just ran into this issue. Thanks!

**Comment by guw** [comment]
I can confirm that the fix solves our proxy issue with https connections.

**Comment by mickaelistria** [comment]
> Are you still involved in this project?

Not any more, sorry.
@longtimeago is now doing most (if not all) the release work.

**Comment by longtimeago** [comment]
Will try to take care soon. Hard times ..

**Pull request merged**
