### PR TITLE
#68 Movie classes to internal package and rise the version

### PR DESCRIPTION
**Pull request by longtimeago**
#68 Movie classes to internal package and rise the version

### CODE REVIEW

**Comment by mickaelistria** [comment]
About the package, I believe com.googlecode.downloadmavenplugin would be better. However I'm not sure about that. What do you think?

**Comment by longtimeago** [comment]
@mickaelistria I've checked package names if many other plugins in the official maven repo.
Haven't found any with joined plugin name as a package name. All tend to use the same pattern:
```
packageName = orgPrefix + pluginName.replaceAll("-", ".")
```

The pros of your variant - package name is shorter by 3 char
The pros of my variant - readability

Usually, I'm for readability :)

**Comment by mickaelistria** [comment]
Ok, thanks for checking that. The benefit I had in mind with a single segment is that I find the structure maps better the project as we do not want to have subpackages under "download" or "maven" packages here, so a single segment makes it clearer that it's not a hierarchy.
Anyway, now it's internal, so it will be easy to change our mind later if this becomes an issue ;)

**Comment by longtimeago** [comment]
@mickaelistria perfect! Thank you! :+1:

**Pull request merged**
