### PR TITLE
Added an example CI config

### PR DESCRIPTION
**Pull request by ajarmoniuk**
Please integrate this so that we have CI flows running upon pull requests.

### CODE REVIEW

**Review by longtimeago — APPROVED** [review]
@ajarmoniuk awesome contribution! :+1: 
Thank you!

**Comment by longtimeago** [comment]
@ajarmoniuk do you have an acsess to https://github.com/maven-download-plugin/maven-download-plugin/actions/runs/4751800980 ?

**Comment by ajarmoniuk** [comment]
Yes. The two tests are failing because the test is trying to download a resource that no longer exists on the server. That's why I modified those two tests in my other PR. 

I'm also preparing another PR to replace all such tests (retrieving resources from some outside world servers) with resources served by the mock repository manager.

**Comment by ajarmoniuk** [comment]
Yes. The two tests are failing because the test is trying to download a resource that no longer exists on the server. That's why I modified those two tests in my other PR. 

I'm also preparing another PR to replace all such tests (retrieving resources from some outside world servers) with resources served by the mock repository manager.

**Comment by longtimeago** [comment]
> I'm also preparing another PR to replace all such tests (retrieving resources from some outside world servers) with resources served by the mock repository manager.

@ajarmoniuk would be really awesome to merge this PR before others

**Pull request merged**
