### PR TITLE
Support Follow Redirects

### LINKED ISSUE #180: Support Follow redirects
The `WGet` Mojo does not support Follow Redirects.

Eg. trying to fetch https://www.jbang.dev/releases/latest/download/version.txt will fail

### PR DESCRIPTION
**Pull request by gastaldi**
Fixes #180

### CODE REVIEW

**Comment by gastaldi** [comment]
I'd appreciate if someone could review, merge this PR and cut 1.6.2 (in this order) 😉

**Comment by gastaldi** [comment]
Alright, I'll go ahead and merge it and release since I really need this feature.

**Comment by longtimeago** [comment]
@gastaldi thanks for the contribution!
Sorry, missed your initial notification. Next time, please, ping me once again if I didn't answer within a day :)
And it would be nice if you follow our release procedure https://github.com/maven-download-plugin/maven-download-plugin/wiki

**Comment by gastaldi** [comment]
@longtimeago ah-ha thanks! I was looking for these instructions since it's been a long time since I released it. Except for the site deploy, I think I did it all right?

**Comment by longtimeago** [comment]
@gastaldi yup :)

**Pull request merged**
